### ISSUE TITLE
Дополнить варианты объектов для привзяки задач в Task.php 

### ISSUE THREAD

**Issue by s-belichenko** [nabarabane/amocrm#13]
https://developers.amocrm.ru/rest_api/tasks_set.php

По ссылке выше можно найти, что параметр add/element_type может быть принимать занчения не только 1/2, но и 3. Соответственно, Task.php можно дополнить в этом месте:
```
const TYPE_CONTACT = 1; // Првязка к контакту
const TYPE_LEAD = 2; // Привязка к сделке
```

**Comment by webdenis77** [comment]
https://github.com/nabarabane/amocrm/issues/12
