### ISSUE TITLE
Невозможно выполнить запрос к API

### ISSUE THREAD

**Issue by maks-okhmatenko** [nabarabane/amocrm#3]
При попытке выполнения любого запроса к API вылазит следующая ошибка. 
Настроено все абсолютно так же, как и в версии 1.0

Fatal error: Uncaught exception 'Exception' with message '{"http_code":401,"response":"Пользователь с данным логином для данного аккаунта не найден. Пожалуйста, для регистрации обратитесь к владельцу аккаунта","description":""}' in /var/www/html/vendor/nabarabane/amocrm/src/Handler.php:103 Stack trace: #0 /var/www/html/index.php(19): AmoCRM\Handler->request(Object(AmoCRM\Request)) #1 {main} thrown in /var/www/html/vendor/nabarabane/amocrm/src/Handler.php on line 103

UPDATE: 
Проблема была в том, что папка config имела неправильные права доступа. Думаю стоит добавить такую проверку в код.

**Comment by webdenis77** [comment]
Согласен, проверку добавил.
