### ISSUE TITLE
Cookie путь

### ISSUE THREAD

**Issue by RevProg** [nabarabane/amocrm#5]
В запросе указан пусть к файлу cookie вбитый в как параметр метода со стандартным значением. На разных серверах путь к временной папке может быть разный. Есть вариант сделать его параметром конструктора?

**Comment by webdenis77** [comment]
Пока не до конца не понимаю, о какой "временной папке" идет речь?
Cookie.txt пишется в директорию "config" при первом авторизационном запросе к amocrm.

``` php
__DIR__.'/../config/cookie.txt
```

Можешь привести пример, когда это не работает?

**Comment by RevProg** [comment]
Прошу прощения. Я не глядя перепутал репозиторий.
