### ISSUE TITLE
Как установить без Composer?

### ISSUE THREAD

**Issue by sashabeep** [nabarabane/amocrm#7]
Есть ли возможность завести то же самое на шареде?

**Comment by s-belichenko** [comment]
Отвечу за автора: есть, просто скачайте пакет себе на шаред. При условии, что ваш шаред поддерживает нужную версию php и прочее необходимое, все пройдет удачно.

**Comment by sashabeep** [comment]
Так того самого autoload.php нету в репе :)

**Comment by s-belichenko** [comment]
Можно и композер скачать, кто мешает :) Или же подключать классы не через автолоадер, а по старинке.

**Comment by webdenis77** [comment]
Все верно, без композера - только по старинке через require

``` php
require 'amocrm/src/Handler.php';
require 'amocrm/src/Request.php';
require 'amocrm/src/Contact.php'; // и т.д.
```

Закрываю.
